# Generated by Django 2.0.6 on 2018-06-29 03:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('cottage_number', models.CharField(max_length=5)),
                ('unique_key', models.UUIDField(default=uuid.uuid4, help_text='Cottage ID', primary_key=True, serialize=False)),
                ('payment_status', models.CharField(blank=True, choices=[('p', 'Paid'), ('d', 'Due')], default='d', help_text='Rent Status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cottage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.Cottage')),
            ],
        ),
    ]
