# Generated by Django 2.0.6 on 2018-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auto_20180630_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='unique_key',
            field=models.CharField(default='00000', max_length=5, primary_key=True, serialize=False),
        ),
    ]
