# Generated by Django 2.0.6 on 2018-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_auto_20180701_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='unique_key',
            field=models.TextField(default='00000', max_length=5, primary_key=True, serialize=False),
        ),
    ]
