# Generated by Django 2.0.6 on 2018-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_auto_20180701_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='unique_key',
            field=models.IntegerField(default='00000', primary_key=True, serialize=False),
        ),
    ]
